### PR TITLE
[16.0][IMP] lighting: solve image resolution limit

### PR DESCRIPTION
**Pull request by FrankC013**

### CODE REVIEW

**Review by eantones — CHANGES_REQUESTED** [review]
Sa we discussed, use context to avoid the verification only if it comes from the importation tool

**Comment by eantones** [comment]
@FrankC013 please check it out, you almost had it...

**Comment by FrankC013** [comment]
Great! The code is very similar to the one i was developing. We forgot to discuss that any image insertion in the attachment or the product should skip this restriction (even if it didn't come from lighting.import.attachment). LGTM :+1:

**Comment by eantones** [comment]
@FrankC013 It's not **any** image, so please don't misinterpret the situation. It specifically concerns the one related to lighting, the restriction still applies in Odoo. The issue is originated from lighting, not from importing attachments, thus the solutions should be targeted at the lighting. First we need to know where the problem really is. If you attempted to import a large attachment into the lighting system without having the import module attachment installed, the issue would have occurred regardless.
Regarding the code, it's not only very similar, the monkey patch part is exactly your code, the one you got from base_sparse_field, but it was incomplete and that's why it didn't work. Debugging the compute methods you mentioned was essential to determine where to place the context to complete the code. This step was crucial for making it work, and you were very close to resolving it. In the future, I encourage you to persist, as you might be nearer to a breakthrough than it appears. Let’s take this as a learning opportunity to push your limits and thoroughly test your solutions.

**Comment by FrankC013** [comment]
@eantones I had understood it, i must have explained myself poorly. 

> We forgot to discuss that any image insertion in the attachment or the product should skip this restriction

I was referring to any image in the lighting.attachment or lighting.product of the lighting module. I know the restriction is still respected in Odoo.  Anyway, the IMP is fine

**Comment by eantones** [comment]
I'm going around with this issue, and although it works well, now that we know the problem is not with the product_attachment but with the lighting, there's still something that doesn't quite fit in this solution. I'll keep thinking about it; it must be something very basic

**Comment by eantones** [comment]
I know why it doesn't quite fit!!! :-). At first, we thought it was a problem with the lighting attachment and we were focusing on line https://github.com/nuobit/lighting-vertical/blob/bbc4cc0d99e6a2a96c8ba7cc6b89a165e8616abe/lighting_import_attachment_product/models/lighting_import_attachment_file_product.py#L169, looking back in the call stack to find where to insert the context. Believing it was a problem with the lighting attachment, we needed to create a solution that only affected the import attachment, so we started with the monkey_patch of verify_resolution to only affect the import attachment. You initially provided a solution that placed verify_resolution in all the lighting fields. We rejected this solution at first because if it was a problem with the import attachment, we couldn't solve it in the lighting. The current solution doesn't quite fit because it's solving the problem by following the approach that we only want the change to affect the import product, whereas now we know the problem is with the lighting. If we had realized from the start that the problem was with the lighting and not the import product, we would have accepted the first simple solution of placing verify_resolution directly in the lighting fields. This highlights the importance of identifying where the problem is initially to address it directly. In conclusion, we added verify_resolution to the fields, the first solution we already had.

**Comment by FrankC013** [comment]
You're right, I'll make the change myself. In the end, the verify_resolution will only affect images from the lighting, and since it's normal to attach images with those specifications, it should apply directly to the field.

**Review by eantones — APPROVED** [review]

**Pull request merged**
